// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZambarakUz.DataAccess.Context;

#nullable disable

namespace ZambarakUz.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("User", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ALIAS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BARCODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CLIENT_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DATE_IN")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DATE_OUT")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FONT_SIZE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("GROUP_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<bool?>("IS_KICKED")
                        .HasColumnType("bit");

                    b.Property<string>("LOGIN_FOR_KKM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD_FOR_KKM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECTION_UID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("ZambarakUz.DataAccess.Entites.UserGroup", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<bool?>("IS_SUPER")
                        .HasColumnType("bit");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("USERS_GROUPS");
                });

            modelBuilder.Entity("ZambarakUz.DataAccess.Entities.Client", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BARCODE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BIRTHDAY")
                        .HasColumnType("datetime2");

                    b.Property<string>("COMMENT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATE_ADD")
                        .HasColumnType("datetime2");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GROUP_UID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.HasIndex("GROUP_UID");

                    b.ToTable("CLIENTS");
                });

            modelBuilder.Entity("ZambarakUz.DataAccess.Entities.ClientGroup", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DISCOUNT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IS_DELETED")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_NON_USE_BONUS")
                        .HasColumnType("bit");

                    b.Property<bool>("IS_SUPPLIER")
                        .HasColumnType("bit");

                    b.Property<decimal>("MAX_SUM_CREDIT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRICE_UID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UID");

                    b.ToTable("CLIENTS_GROUPS");
                });

            modelBuilder.Entity("ZambarakUz.DataAccess.Entities.Client", b =>
                {
                    b.HasOne("ZambarakUz.DataAccess.Entities.ClientGroup", "GROUP_")
                        .WithMany()
                        .HasForeignKey("GROUP_UID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GROUP_");
                });
#pragma warning restore 612, 618
        }
    }
}
